"""
restore_validator.py — checks compatibility of database backups against current app version.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from zipfile import ZipFile

from trackora.core.schema_version import SchemaVersion

logger = logging.getLogger(__name__)


class RestoreValidator:
    """Validates the schema and application version compatibility of a backup."""

    @staticmethod
    def verify_compatibility(backup_path: Path, current_schema_version: SchemaVersion) -> tuple[bool, str | None]:
        """Verify the compatibility of the backup archive file.

        Args:
            backup_path: Path to the backup ZIP.
            current_schema_version: SchemaVersion representing the current DB capabilities.

        Returns:
            A tuple (is_compatible, error_message).
        """
        try:
            with ZipFile(backup_path, "r") as zf:
                if "MANIFEST.json" not in zf.namelist():
                    return False, "MANIFEST.json is missing from the backup archive."

                manifest = json.loads(zf.read("MANIFEST.json").decode("utf-8"))

                # Verify backup is generated by Trackora
                trackora_version = manifest.get("trackora_version")
                if not trackora_version:
                    return False, "Backup does not contain Trackora version metadata."

                # Verify schema compatibility
                backup_schema_str = manifest.get("schema_version")
                if not backup_schema_str:
                    return False, "Backup is missing database schema version information."

                try:
                    backup_schema = SchemaVersion.from_string(backup_schema_str)
                except Exception:
                    return False, f"Invalid schema version in backup manifest: {backup_schema_str}"

                # Abort if database schema version in backup is newer than the app can support
                if backup_schema > current_schema_version:
                    return False, (
                        f"Incompatible backup schema version: {backup_schema_str}. "
                        f"Current application supports up to schema version {current_schema_version}."
                    )

            return True, None
        except Exception as exc:
            return False, f"Failed to parse backup archive compatibility: {exc}"
