"""
scripts/bump_version.py — Centralized Version Artifact Generator
=================================================================

Reads the application version from the single source of truth:
    trackora/__init__.py  →  __version__ = "MAJOR.MINOR.PATCH"

Then regenerates all derived artifacts:
    1. version_info.txt           — PyInstaller Windows resource block
    2. installer/version.iss      — Inno Setup preprocessor include

Usage (run from the repository root):
    python scripts/bump_version.py

No arguments are needed.  Run this once before every build:
    python scripts/bump_version.py
    pyinstaller Trackora.spec
    iscc installer/Trackora.iss

Exit codes:
    0 — success
    1 — version could not be read or is malformed
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths (all relative to the repository root)
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
INIT_FILE = REPO_ROOT / "trackora" / "__init__.py"
VERSION_INFO_FILE = REPO_ROOT / "version_info.txt"
INSTALLER_VERSION_FILE = REPO_ROOT / "installer" / "version.iss"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_VERSION_RE = re.compile(
    r'^__version__\s*=\s*["\']([^"\']+)["\']', re.MULTILINE
)
_SEMVER_RE = re.compile(r"^\d+\.\d+\.\d+$")


def read_version() -> str:
    """Read ``__version__`` from trackora/__init__.py without importing it."""
    source = INIT_FILE.read_text(encoding="utf-8")
    match = _VERSION_RE.search(source)
    if not match:
        print(
            f"ERROR: could not find __version__ in {INIT_FILE}", file=sys.stderr
        )
        sys.exit(1)
    version = match.group(1)
    if not _SEMVER_RE.match(version):
        print(
            f"ERROR: __version__ = {version!r} is not MAJOR.MINOR.PATCH",
            file=sys.stderr,
        )
        sys.exit(1)
    return version


def version_tuple(version: str) -> tuple[int, int, int]:
    """Convert ``"2.0.2"`` → ``(2, 0, 2)``."""
    parts = version.split(".")
    return int(parts[0]), int(parts[1]), int(parts[2])


# ---------------------------------------------------------------------------
# Generators
# ---------------------------------------------------------------------------

def write_version_info(version: str) -> None:
    """Regenerate version_info.txt for PyInstaller."""
    major, minor, patch = version_tuple(version)
    content = f"""\
# UTF-8
#
# For more details about fixed file info 'ffi' see:
# https://learn.microsoft.com/en-us/windows/win32/menurc/versioninfo-resource
#
# Auto-generated by scripts/bump_version.py — DO NOT EDIT
# Source of truth: trackora/__init__.py
VSVersionInfo(
  ffi=FixedFileInfo(
    # filevers and prodvers should be always a tuple of four items: (1, 0, 0, 0)
    filevers=({major}, {minor}, {patch}, 0),
    prodvers=({major}, {minor}, {patch}, 0),
    # Contains a bitwise combination of the file type flags
    mask=0x3F,
    flags=0x0,
    # OS type:
    # 0x0004 - Windows NT
    OS=0x40004,
    # File type:
    # 0x0001 - Application
    fileType=0x1,
    # Nothing
    subtype=0x0,
    # Date and time stamps (optional)
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
           [StringStruct(u'CompanyName', u'Trackora'),
           StringStruct(u'FileDescription', u'Trackora - Automatic Gaming Session Tracker'),
             StringStruct(u'FileVersion', u'{version}'),
           StringStruct(u'InternalName', u'Trackora'),
           StringStruct(u'LegalCopyright', u'Copyright (c) 2026 Trackora. All rights reserved.'),
           StringStruct(u'OriginalFilename', u'Trackora.exe'),
           StringStruct(u'ProductName', u'Trackora'),
                        StringStruct(u'ProductVersion', u'{version}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [0x0409, 0x04B0])])
  ]
)
"""
    VERSION_INFO_FILE.write_text(content, encoding="utf-8")
    print(f"  [OK] {VERSION_INFO_FILE.relative_to(REPO_ROOT)}")


def write_installer_version(version: str) -> None:
    """Regenerate installer/version.iss for Inno Setup."""
    INSTALLER_VERSION_FILE.parent.mkdir(parents=True, exist_ok=True)
    content = (
        "; Auto-generated by scripts/bump_version.py — DO NOT EDIT\n"
        "; Source of truth: trackora/__init__.py\n"
        f'#define MyAppVersion "{version}"\n'
    )
    INSTALLER_VERSION_FILE.write_text(content, encoding="utf-8")
    print(f"  [OK] {INSTALLER_VERSION_FILE.relative_to(REPO_ROOT)}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    version = read_version()
    major, minor, patch = version_tuple(version)

    print(f"Trackora version: {version}  ({major}, {minor}, {patch}, 0)")
    print("Regenerating artifacts:")
    write_version_info(version)
    write_installer_version(version)
    print("Done.")


if __name__ == "__main__":
    main()
